# Generated by Django 5.0.4 on 2026-05-25 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('message_received', 'Message Received'), ('message_sent', 'Message Sent'), ('lead_created', 'Lead Created'), ('booking_confirmed', 'Booking Confirmed'), ('human_takeover', 'Human Takeover'), ('ai_failure', 'AI Failure')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(default='instagram', max_length=50)),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['event_type'], name='analytics_e_event_t_acfd0a_idx'), models.Index(fields=['created_at'], name='analytics_e_created_7b5fb3_idx')],
            },
        ),
    ]
