# Generated by Django 5.0.4 on 2026-05-25 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('message_received', 'Message Received'), ('intent_detected', 'Intent Detected'), ('car_recommended', 'Car Recommended'), ('booking_started', 'Booking Started'), ('booking_completed', 'Booking Completed'), ('handoff_triggered', 'Handoff Triggered')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at_hour', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('ai_messages', models.IntegerField(default=0)),
                ('human_messages', models.IntegerField(default=0)),
                ('unique_conversations', models.IntegerField(default=0)),
                ('new_leads', models.IntegerField(default=0)),
                ('bookings_created', models.IntegerField(default=0)),
                ('bookings_completed', models.IntegerField(default=0)),
                ('revenue_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_response_time_seconds', models.FloatField(default=0)),
                ('ai_handoff_count', models.IntegerField(default=0)),
                ('ai_confidence_avg', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsEvent',
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['event_type', 'created_at'], name='analytics_c_event_t_b17a71_idx'),
        ),
    ]
