# Generated by Django 5.0.4 on 2026-05-25 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '__first__'),
        ('conversations', '0001_initial'),
        ('instagram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='lead', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_car_type', models.CharField(blank=True, max_length=100)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cars.car')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='instagram.instagramcontact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
            ],
            options={
                'db_table': 'bookings_booking',
                'indexes': [models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['pickup_date'], name='bookings_bo_pickup__2a95b5_idx'), models.Index(fields=['contact'], name='bookings_bo_contact_91af10_idx')],
            },
        ),
    ]
