# Generated by Django 5.0.4 on 2026-05-25 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('profile_pic', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('tj', 'Tajik')], default='en', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'instagram_contact',
            },
        ),
    ]
